### ISSUE TITLE
run "hexo edit" failed: Error:  [ReferenceError: Promise is not defined]

### ISSUE THREAD

**Issue by tinyfox266** [greg-js/hexo-cli-extras#1]
Hi,

I try to use the command "hexo edit", and then i'm having the following issue:

```
INFO  Start processing
Error:  [ReferenceError: Promise is not defined]
```

My node.js version is v0.10.29 and the hexo version is v3.2.0

Thanks!

**Comment by greg-js** [comment]
Hi,

I published a fix! It should work if you update the package, let me know if there's a problem :)

Alternatively, updating node to 0.12+ (latest version is 6.1.2) would resolve your issue as well thanks to native promises

**Comment by greg-js** [comment]
Hi, did you get round to testing if the fix worked for you? I'll close the issue since this should be fixed, but feel free to reopen if for whatever reason it still doesn't work. Thanks for reporting the bug!
